server:
  port: 9999
  context-path: /spingboot
  jsp-servlet:
    init-parameters:
     development: true
spring:
  http:
    multipart:
      max-file-size: 1024MB
  mvc:
    view:
      prefix: /
      suffix: .jsp